### PR TITLE
Fixing depreciated react navigation methods

### PR DESCRIPTION
**Pull request by felipemillhouse**
Just fix depreciated methods on new react navigation version.
screen shot 2019-01-15 at 4 03 38 pm

### CODE REVIEW

**Comment by chrfalch** [comment]
Hi @felipemillhouse, sorry for the delay in answering - thanks for the PR. I'm having some issues with the commit due to formatting changes - would it be possible to only commit the relevant changes?

**Comment by jan-happy** [comment]
@felipemillhouse Your changes would be really helpful! Could you resolve the conflicts? Thank you very much!

**Comment by felipemillhouse** [comment]
I'll do that tonight 👍🏻 the formatting changes was the prettier in my vscode, sorry.

**Comment by felipemillhouse** [comment]
Hey @jan-happy the fram-x team committed a new version 3 days ago fixing "Added support for React Navigation 3.0" so this my changes is not necessary anymore, just update the project and done ;)

**Comment by chrfalch** [comment]
Closing

**Pull request closed without merging**
