### PR TITLE
Fix for the deprecated Transitioner import Issue #137

### PR DESCRIPTION
**Pull request by lbaldy**
I tested that using the sample project the warning went away, seems to be okay. Had issues publishing it. If you have any contributor guide I'd be more than happy to follow.

### CODE REVIEW

**Comment by joshnissenbaum** [comment]
```
Error: jest-haste-map: @providesModule naming collision:
Duplicate module name: react-native
```

When pulling in your pull request

**Comment by jan-happy** [comment]
@lbaldy: Thanks for your fix, I'm running into the same warning. Could you fix your pr?

**Comment by lbaldy** [comment]
Yes, sorry. I've been a bit slammed recently. I'll review and let you know as soon as I can.

**Comment by lbaldy** [comment]
I think this can be closed. It seems to be already fixed via: https://github.com/fram-x/FluidTransitions/commit/77fc193eb832341d874697dd279868c9aae4d8c9

**Pull request closed without merging**
